name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  automation:
    name: Trigger Automation Script
    runs-on: ubuntu-latest
    
    steps:
      - name: Automation Check
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
         owner: mohankiran
         repo: sol-cpi-commercial-pool-automation
         github_token: ${{ secrets.ACTIONS_KEY }}
         workflow_file_name: maven.yml

  build:
    needs: [automation]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Step 2
        run: echo "it worked"
