# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Trigger Workflow and Wait
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
            owner: mohankiran
            repo: sol-cpi-commercial-pool-automation
            github_token: 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
            workflow_file_name: maven.yml
