# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - run: echo "Triggering from UI"
      - name: Automation Check
        id: automation-check
        run: |
            curl -X POST https://api.github.com/repos/mohankiran/sol-cpi-commercial-pool-automation/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -u ${{ secrets.ACTIONS_KEY }} \
            --data '{"event_type": "Automation Workflow", "client_payload": { "repository": "https://github.com/mohankiran/sol-cpi-commercial-pool-automation" }}'
            
      - name: Run other steps
        if: steps.automation-check.outcome == 'success'
        run: |
          echo "Status is success"
