name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: ["Automation Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - run: echo "Triggering from UI"
      - name: Automation Check
        id: automation_check
        run: |
            curl -X POST https://api.github.com/repos/mohankiran/sol-cpi-commercial-pool-automation/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -u ${{ secrets.ACTIONS_KEY }} \
            --data '{"event_type": "Automation Workflow", "client_payload": { "repository": "https://github.com/mohankiran/sol-cpi-commercial-pool-automation" }}'
            
      - name: Wait for Automation Workflow
        id: wait-for-automation
        run: |
          echo "Waiting for Automation Workflow completion..."
          while true; do
            response=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" https://api.github.com/repos/mohankiran/sol-cpi-commercial-pool-automation/actions/workflows/maven.yml/runs)
            status=$(echo "$response" | jq -r '.status')
            conclusion=$(echo "$response" | jq -r '.conclusion')
            echo "Default status: $status"
            echo "Default conclusion: $conclusion"
            if [[ "$status" == "completed" ]]; then
              echo "Automation Workflow completed."
              break
            elif [[ "$status" == "in_progress" || "$status" == "queued" ]]; then
              echo "Automation Workflow still in progress. Waiting..."
            else
              echo "Automation Workflow failed or canceled. Exiting..."
            fi

            sleep 30
          done

      - name: Run Other Steps
        if: steps.wait-for-automation.outputs.automation-conclusion == 'success'
        run: echo "We can go further"
